// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",      
  handlers: [
    {
      match: finicky.matchHostnames(["meet.google.com"]),
      browser: "Google Chrome"
    }
  ]
}
