// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",      
  handlers: [
    {
      match: /^https?:\/\/meet\.google\.com.*$/,
      browser: "/Users/nbrubake/Applications/Chrome Apps.localized/Google Meet.app"
    }
  ]
}
