# Minimal Text Template
"$schema" = "https://starship.rs/config-schema.json"

palette = "custom"
add_newline = false

# dir git model context cost reset
format = """
$directory \
$git_branch$git_status \
${env_var.CLAUDE_MODEL} \
${env_var.CLAUDE_CONTEXT} \
${env_var.CLAUDE_COST} \
${env_var.CLAUDE_RATE_5H}\
"""

[directory]
style = "fg:directory"
format = "[$path]($style)"
truncation_length = 2
truncate_to_repo = true

[git_branch]
symbol = ""
style = "fg:git_branch"
format = "[$branch]($style)"

[git_status]
style = "fg:git_status"
format = "[($all_status$ahead_behind)]($style)"

[env_var.CLAUDE_MODEL]
variable = "CLAUDE_MODEL"
format = "[$env_value]($style)"
style = "fg:model"

[env_var.CLAUDE_CONTEXT]
variable = "CLAUDE_CONTEXT"
format = "[$env_value]($style)"
style = "fg:context"

[env_var.CLAUDE_COST]
variable = "CLAUDE_COST"
format = "[$env_value]($style)"
style = "fg:cost"

[env_var.CLAUDE_RATE_5H]
variable = "CLAUDE_RATE_5H"
format = "[(reset $env_value)]($style)"
style = "fg:rate_limit"

## Custom palette
#

# Gruvbox Dark
[palettes.custom]
claude = "#D97757"
claude_bg = "#282828"

directory = "#83a598"
directory_bg = "#282828"

git_branch = "#b16286"
git_status = "#d3869b"
git_bg = "#3c3836"

model = "#458588"
model_bg = "#282828"

context = "#d79921"
context_bg = "#3c3836"

cost = "#689d6a"
cost_bg = "#504945"

rate_limit = "#fe8019"
rate_limit_bg = "#3c3836"
